apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: cilium
    hajimari.io/appName: Actual Budget
    hajimari.io/icon: wallet
spec:
  tls:
    - hosts:
        - budget.kleinsorge.dev
      secretName: actualbudget-tls-certificate
  rules:
    - host: budget.kleinsorge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budget
                port:
                  name: http
