seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Seafile
        hajimari.io/icon: folder-multiple
      hosts:
        - host: &host files.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: seafile-tls-certificate
          hosts:
            - *host
  mariadb:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: latest
    primary:
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: latest
  persistence:
    data:
      enabled: true
      type: nfs
      server: 192.168.1.208
      path: /volume1/kube/seafile
