apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: cilium
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hajimari.io/appName: web
    hajimari.io/icon: web
spec:
  rules:
    - host: &host kindle-weather.kleinsorge.dev
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: kindle-weather-service
                port:
                  number: 80
  tls:
    - secretName: kindle-weather-tls-certificate
      hosts:
        - *host
