librespeed:
  ingress:
    main:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        librespeed.io/enable: 'true'
        hajimari.io/appName: LibreSpeed
        hajimari.io/icon: speedometer
      hosts:
        - host: &host speed.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: librespeed-tls-certificate
          hosts:
            - *host
