kube-ops-view:
  ingress:
    main:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Kube Ops View
        hajimari.io/icon: kubernetes
      hosts:
        - host: &host view.kleinsorge.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kube-ops-view-tls-certificate
          hosts:
            - *host
