photoprism:
  image:
    repository: photoprism/photoprism
    tag: "latest"
    pullPolicy: IfNotPresent
  server:
    debug: "true"
    persistence:
      enabled: true
      importPath: &importPath /assets/photos/import
      originalsPath: &originalsPath /assets/photos/originals
      volumeMounts:
      - name: originals
        mountPath: *originalsPath
      - name: import
        mountPath: *importPath
      volumes:
      - name: originals
        nfs:
          server: 192.168.1.208
          path: /volume1/Media/Memories
          readOnly: true 
      - name: import
        nfs:
          server: 192.168.1.208
          path: /volume1/photo
  ingress:
    enabled: false
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      photoprism.io/enable: 'true'
      hajimari.io/appName: PhotoPrism
      hajimari.io/icon: camera
      nginx.ingress.kubernetes.io/proxy-body-size: "512M"
    hosts:
      - host: &host photos.kleinsorge.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: photoprism-tls-certificate
        hosts:
          - *host
  resources:
    requests:
      memory: 2Gi
